db.orders.aggregate(
    [
        {
            $limit:50
        },
        {
            $lookup:{
                from:"users",
                localField:"user_id",
                foreignField:"_id",
                as:"user_name"
            }
        },
        {
            $unwind:"$user_name"
        },
        {
            $lookup:{
                from:"products",
                localField:"items.product_id",
                foreignField:"_id",
                as:"product_info"
            }
        },
        {
            $unwind:"$product_info"
        },
        {
            $lookup:{
                from:"payments",
                localField:"payment_id",
                foreignField:"_id",
                as:"payment_details"
            }
        },
        {
            $unwind:"$payment_details"
        },
        {
            $lookup:{
                from:"shipping",
                localField:"_id",
                foreignField:"order_id",
                as:"ship"
            }
        },
        {
            $unwind:"$ship"
        },
        {
            $lookup:{
                from:"refunds",
                localField:"_id",
                foreignField:"order_id",
                as:"refund"
            }
        },
        {
            $unwind:"$refund"
        },
        {
            $group:{
                _id:{
                    order_id:"$_id",
                    user_name:"$user_name.first_name",
                    product_details:"$product_info",
                    payment_details:"$payment_details",
                    shipping_status:"$ship.status",
                    refund_amount:"$refund.refund_amount"
                }
            }
        },
        
    ]
)